<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Identity\GLP.Identity.Application\GLP.Identity.Application.csproj" />
      <ProjectReference Include="..\Identity\GLP.Identity.Domain\GLP.Identity.Domain.csproj" />
      <ProjectReference Include="..\Identity\GLP.Identity.Infrastructure\GLP.Identity.Infrastructure.csproj" />
    </ItemGroup>
    
</Project>
